### ISSUE TITLE
Custom Themebook 

### ISSUE THREAD

**Issue by rdsbrazil** [taragnor/city-of-mist#12] opened 2022-03-21 23:40 UTC
I can't use custom themebooks, every time I try to add one to the character sheet it did nothing but crash the character sheet and I can't do anything after, I have to delete the sheet because it would not even open anymore!

**Comment by taragnor** [comment] 2022-03-23 06:21
I tried making a custom themebook and it worked fine when I added it to a character. Do you have any further steps to duplicate the error? I couldn't reproduce the error.

**Comment by rdsbrazil** [comment] 2022-03-23 15:05
i made a video showing!

https://drive.google.com/file/d/1HcH9TbS8yQGaKp0oBkFrsbh59yhV00R0/view?usp=sharing

**Comment by taragnor** [comment] 2022-03-24 11:45
Okay Thanks. I was able to reproduce it. Right now the system requires a reload if you create new themebooks. At some point in the future I will probably add support for adding themebooks without a refresh. 

In the meantime you can fix the problem by simply refreshing your browser window (F5 on most browsers) and it will fix the error. In my tests, the themebook was properly loaded once I refreshed after getting the error.

Let me know if that fixes your issue.

**Comment by rdsbrazil** [comment] 2022-03-24 15:37
It worked!!!
Thank you so much!
Now, one thing I realized is that when you choose a power tag, it is showing also the "deleted" options.

![image](https://user-images.githubusercontent.com/73025261/159953545-1f58e786-ae27-4d61-91b2-9219708151ee.png)

**Comment by taragnor** [comment] 2022-04-05 01:45
The issue should be fixed in the latest update.

**Closed as completed by taragnor** 2022-04-05 01:45 UTC
