### ISSUE TITLE
BUG: Cannot open player character sheets

### ISSUE THREAD

**Issue by CharlesRampant** [taragnor/city-of-mist#59] opened 2024-04-09 09:45 UTC
Hello,

Since updating to the latest version I cannot open any player character sheets. Strangely I _can_ open NPC sheets, and no error messages in console when I do, either, however PC sheets are refusing entirely to open for me. I have restarted the server and disabled all modules, and when I double click on their token I get the following error message in the console, changing only the number for each of the four PCs:

> foundry.js:753 Error: An error occurred while rendering CityCharacterSheet 34. One of original or other are not Objects!
>     at mergeObject (commons.js:2739:13)
>     at _mergeUpdate (commons.js:2803:14)
>     at mergeObject (commons.js:2760:41)
>     at _mergeUpdate (commons.js:2803:14)
>     at mergeObject (commons.js:2760:41)
>     at _mergeUpdate (commons.js:2803:14)
>     at Object.mergeObject (commons.js:2760:41)
>     at CityCharacterSheet._render (foundry.js:5807:19)
>     at CityCharacterSheet._render (foundry.js:6532:17)
>     at CityCharacterSheet.render (foundry.js:5769:10)

When I click on their name in the Actor list I get the following, again changing number for each PC:

> foundry.js:753 Error: An error occurred while rendering CityCharacterSheet 36. Can't create Loadout theme: No valid Loadout theme exists
>     at CityActor.createLoadoutTheme (city-actor.js:1177:19)
>     at CityCharacterSheet.getData (city-character-sheet.js:65:45)
>     at async CityCharacterSheet._render (foundry.js:5812:18)
>     at async CityCharacterSheet._render (foundry.js:6532:5)

**Versions**: Foundry Virtual Tabletop Version 11 Stable Build 315. City of Mist 3.0.1. The only active module is the Forge, which I cannot de-select as it is the host website thingy.

**Comment by CharlesRampant** [comment] 2024-04-09 12:47
![image](https://github.com/taragnor/city-of-mist/assets/37817189/10e5bb6b-6b40-46c9-89cd-8c57c0353a5f)

This also happens in a brand new test world. (Tested this at suggestion of _aMediocreDad_ on Discord)

**Comment by rikmarais** [comment] 2024-04-09 17:10
It's been suggested that this happens due to f81d969ebc18bf036342f6d8db843b047ecbe481 not being included in the original 3.0.1 release 045dcdf6e55137c4944fcb1fb3ed0e9c8161435d

The Forge Bazaar considers versions immutable and downloads the version as soon as it is available (simulating a user who installs as soon as they see the new version) so if the contents of a version were updated after the original release of that version, the Bazaar wouldn't get it.

If that's the case, the issue would be resolved with a v3.0.2 release which bumps the version, indicating to the Bazaar that the package has changed

**Comment by taragnor** [comment] 2024-04-09 17:59
> If that's the case, the issue would be resolved with a v3.0.2 release which bumps the version, indicating to the Bazaar that the package has changed

Ill try doing a 3.0.2 release and we'll see if that fixes it. I've run into issues with Forge compatibility before. It has some odd quirks to it. I personally don't use it, so often those errors slip by.

**Comment by rikmarais** [comment] 2024-04-09 18:11
Thanks! We confirmed that installing as a custom package (not the Bazaar version) worked, so I think the 3.0.2 bump will resolve this issue. 

No pressure, but Forge does offer free accounts for package developers for optional testing. If you're interested in that at all, you would be able to request one by sending an email to `contact@forge-vtt.com` :)

**Closed as completed** 2024-04-17 20:53 UTC
